package app.betar.comm.ui.screens.onboarding

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import app.betar.comm.R
import app.betar.comm.ui.theme.BetarPolygonShapes

/**
 * DESIGN-BRIEF.md §9 screen 3: pre-filled and skippable, keys already generated by then and
 * never mentioned. [onDone] fires with the nickname actually in effect, whether the user typed
 * one or left the generated default; [NicknameStore] is the only persistence, there is no
 * account or profile system for this to belong to.
 */
@Composable
fun NicknameScreen(onDone: () -> Unit) {
    val context = LocalContext.current
    var nickname by remember { mutableStateOf(NicknameStore.loadOrGenerate(context)) }

    Column(Modifier.fillMaxSize().padding(20.dp)) {
        Text(stringResource(R.string.onboarding_nickname_title), style = MaterialTheme.typography.headlineMedium)
        androidx.compose.foundation.layout.Spacer(Modifier.height(12.dp))
        Text(stringResource(R.string.onboarding_nickname_subtitle), style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurfaceVariant)
        androidx.compose.foundation.layout.Spacer(Modifier.height(18.dp))

        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(76.dp)
                .clip(MaterialTheme.shapes.large)
                .background(MaterialTheme.colorScheme.surface)
                .border(2.dp, MaterialTheme.colorScheme.primary, MaterialTheme.shapes.large)
                .padding(horizontal = 20.dp),
            contentAlignment = Alignment.CenterStart,
        ) {
            BasicTextField(
                value = nickname,
                onValueChange = { nickname = it },
                textStyle = MaterialTheme.typography.titleLarge.copy(color = MaterialTheme.colorScheme.onSurface),
                singleLine = true,
            )
        }
        androidx.compose.foundation.layout.Spacer(Modifier.height(14.dp))

        Row(verticalAlignment = Alignment.CenterVertically) {
            Box(Modifier.size(22.dp).clip(BetarPolygonShapes.cookie9).background(MaterialTheme.colorScheme.tertiary))
            androidx.compose.foundation.layout.Spacer(Modifier.size(10.dp))
            Text(stringResource(R.string.onboarding_nickname_picked_for_you), style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        androidx.compose.foundation.layout.Spacer(Modifier.height(16.dp))

        Box(
            modifier = Modifier
                .fillMaxWidth()
                .clip(MaterialTheme.shapes.medium)
                .background(MaterialTheme.colorScheme.secondaryContainer)
                .padding(18.dp),
        ) {
            Text(stringResource(R.string.onboarding_nickname_privacy_note), style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSecondaryContainer)
        }

        androidx.compose.foundation.layout.Spacer(Modifier.weight(1f))

        Button(
            onClick = {
                NicknameStore.save(context, nickname)
                onDone()
            },
            modifier = Modifier.fillMaxWidth().height(56.dp),
        ) { Text(stringResource(R.string.onboarding_nickname_start_button)) }

        OutlinedButton(
            onClick = {
                NicknameStore.save(context, nickname)
                onDone()
            },
            modifier = Modifier.fillMaxWidth().height(56.dp).padding(top = 8.dp),
        ) { Text(stringResource(R.string.onboarding_nickname_skip)) }
    }
}
